### ISSUE TITLE
Dataset processing problem

### ISSUE THREAD

**Issue by morninghut** [tinglyfeng/sentiment_pretraining#4]
Thank you for your excellent work. While reproducing your paper and code, I encountered some issues with the data. Specifically, I am trying to reproduce the color part of the ST task. The experimental section in the paper mentions that the ST part is based on place365.

> All the tasks in ST and HO pre-training are performed on Places365 dataset

So, I downloaded the place365 dataset and used the official data segmentation file. I modified the corresponding configuration file accordingly. However, when I ran the ``pre_training.sh``, I encountered the following error: 
```python
Traceback (most recent call last):
  File "/home/user/sentiment_pretraining/pre_training/main_multiitask.py", line 163, in <module>
    main()
  File "/home/user/sentiment_pretraining/pre_training/main_multiitask.py", line 65, in main
    main_worker(cfg['device']['gpu'], ngpus_per_node, cfg)
  File "/home/user/sentiment_pretraining/pre_training/main_multiitask.py", line 101, in main_worker
    train_loader, test_loader, train_sampler = get_dataloader(cfg)
  File "/home/user/sentiment_pretraining/pre_training/loader.py", line 11, in get_dataloader
    train_dataset =  dataset.multiTaskDataset('train',cfg)
  File "/home/user/sentiment_pretraining/pre_training/dataloader/dataset.py", line 42, in __init__
    self.parse_data(cfg)
  File "/home/user/sentiment_pretraining/pre_training/dataloader/dataset.py", line 65, in parse_data
    label = int(elems[1])
IndexError: list index out of range
```
Upon inspecting the mentioned ``multiTaskDataset.parse_data()`` function in the Traceback, I noticed this section of code: 
```python
if any([task in ['color', 'sr', 'scene', 'jigsaw'] for task in self.tasks]):
...
    for line in lines:
        print(f'line: {line}')
        elems = line.split('   ')
        img_name = elems[0]
        label = int(elems[1])
        img_path = os.path.join(self.scene_data_root, img_name)
        self.scene_img_paths.append(img_path)
        self.scene_labels.append(label)
```
It seems that it expects each line of the file ``train.txt``(which is the offical train_split file of Place365) to contain two elements: label and img_name, separated by three spaces. However, upon checking the dataset file, I found that each line has a structure like this: 
```csv
train/field-cultivated/00002789.jpg
```
I don't know how to fix the problem. I would like to provide my ``pretrain_st.yaml`` if you need. I would appreciate for any possible assistance.

**Comment by yylong10** [comment]
I downloaded file "places365standard_easyformat.tar", and fix this bug by modifying the source code.
```
    def parse_data(self, cfg):
        if any([task in ['color', 'sr', 'scene', 'jigsaw'] for task in self.tasks]):
            if self.split == 'train':
                split_txt = cfg['dataset']['scene']['train_split']
            elif self.split == 'test':
                split_txt = cfg['dataset']['scene']['test_split']
            else:
                raise ValueError
            self.scene_data_root = cfg['dataset']['scene']['data_root']
            self.scene_img_paths = []
            self.scene_labels = []

            def list_subdir(dir):
                subdir = []
                for item in os.listdir(dir):
                    path = os.path.join(dir, item)
                    if os.path.isdir(path):
                        subdir.append(path)
                return subdir

            if not os.path.exists(os.path.join(self.scene_data_root, "category.txt")):
                scene_category = []
                for subset in list_subdir(self.scene_data_root):
                    scene_category.extend(list_subdir(os.path.join(self.scene_data_root, subset)))
                scene_category = list(map(lambda x: x.split(os.sep)[-1], scene_category))
                scene_category = sorted(list(set(scene_category)))
                with open(os.path.join(self.scene_data_root, "category.txt"), "w") as f:
                    f.writelines(line + "\n" for line in scene_category)
            else:
                with open(os.path.join(self.scene_data_root, "category.txt")) as f:
                    scene_category = list(map(lambda x: x.strip(), f.readlines()))

            lines = read_txt(os.path.join(self.scene_data_root, split_txt))
            for line in lines:
                label = scene_category.index(line.split('/')[1])
                img_path = os.path.join(self.scene_data_root, line)
                self.scene_img_paths.append(img_path)
                self.scene_labels.append(label)
```

**Comment by yylong10** [comment]
I just find offical method, run 'sentiment_pretraining\pre_training\data\tools\make_label.py'.

**Comment by morninghut** [comment]
Thank you very much for your prompt reply and assistance! I will try to see if this works.

**Comment by morninghut** [comment]
@1y9y9l4 Thank you very much for your kind assistance. I successfully got the files ``train_lbl.txt`` and ``val_lbl.txt`` after running the script ``sentiment_pretraining\pre_training\data\tools\make_label.py``. I was able to achieve success by using the original function ``multiTaskDataset.parse_data()``. 

Once again, I sincerely appreciate your generous support.
